### ISSUE TITLE
Error when login with Google Oauth

### ISSUE THREAD

**Issue by sbounmy** [qawolf/qawolf#1101]
## Bug description

_Describe the issue, including screenshots where helpful._

Given I want to test my google sign-in
When I create a qawolf test
And I try to sign my user in
Then it shows an error

<img width="469" alt="Screenshot 2021-03-01 at 10 13 01" src="https://user-images.githubusercontent.com/159814/109476189-e7e1da00-7a76-11eb-90e0-1a445092a659.png">
## Steps to reproduce

https://www.qawolf.com/test/cklqcq8rk000008l21fb3710l

When we test manually it does work : https://hackerhouse.paris/version-test/login

**Comment by flaurida** [comment]
Hi @sbounmy thanks for pointing this out! Sign in with Google is tricky for automated tests because they can detect that the test is automated and can block that activity.

In this scenario I would consider bypassing sign in with Google. Happy to help set that up with you, please choose a time [here](https://calendly.com/jperl/30min?month=2021-03) if you are interested.
