### ISSUE TITLE
Store tests and helpers in git & support test branches

### ISSUE THREAD

**Issue by flaurida** [qawolf/qawolf#1202]
Allow connecting a github project to use as the source of truth.

Allow choosing a branch when editing and running tests.

Allow test name, code changes, and helpers changes to be committed to a branch.

**Comment by Fluidbyte** [comment]
Having a single set of tests is becoming a bit of a blocker for us, hopefully this helps illustrate:

We do all our manual QA and user acceptance testing on a branch called `staging`, the last stop before production deploys. We have all of our tests setup for this branch and right now they are passing

We are working on a branch (we'll call it) `feature-a` which will break a number of the tests.

When we merge `feature-a` our build/tests will be failing. There's really no good way to get out ahead of this. We write unit tests on our branches and ensure those are passing before merge but with a single set of QAE tests there's no way to use QAWolf to manage these new tests.

The one idea that keeps rolling around in my head is if I could maintain tests in the repo - then QAWolf would be able to pull those in based on a branch I've selected in the UI to test against, maybe a structure similar to other testing practices:

```
project_root
    __qawolf__
        _helpers
            helper-a.js
            helper-b.js
      _tests
            test-a.test.js
            test-b.test.js
```

**Comment by drumnation** [comment]
This is really critical for us too.  Now that developers are using an http-tunnel to be able to run the tests on their own branch we can see where there are broken tests due to the new changes (not bugs).  If a developer edits the tests so that they do not break on their branch, that same instance of tests will then fail in CI for any merges that come in until the PR with the updates is merged in.

When it was me by myself this was doable, but as soon as I added a second developer to the mix everything got very confusing.  We need to be able to sync instances of the test code with matching code from our app and the only way I can really think to do that properly is by keeping the tests in our repo next to our app in github.  

Maybe a drop down somewhere in the QAwolf gui that selects a branch for editing and test running?

Developers are going to want these e2e tests to work like unit tests in that they will want all the lights green on their PR before submitting it, and they will want all the lights green after it merges.  Without the above system there is a mandatory period where all the tests are broken after every merge.  

Imagine if all 5 developers were updating the same set of tests to work with their PR branches... the chaos that would ensue for each other developer having the tests on their branches change as well as the tests covering the main branch.

If the code was stored in the app repo this would also allow the option of editing the tests in your code editor of choice already setup with linting, prettier, and ability to split the code windows and view more than 1 file at a time.  I can see myself using the site editor most of the time, but occasionally formatting it and debugging it in the full editor.

**Comment by jperl** [comment]
I agree to support this we need to establish a file structure that works well with git. Then use that as the source of truth for the dashboard / editor.

This will allow you to use git to handle merge conflicts/ track version history / and include test changes as part of the standard git flow (open PR, etc).

Here is a proposed file structure.

- `qawolf/` folder at the root of the git repo
- A test file would be anything with the `.test.js` prefix. You can put these in a folder or not.
- `qawolf/helpers` is a folder that will store the helpers. For now it will just be one global helpers file. In helpers v2 you can add as many helpers as you want.
 
``
qawolf/createAccount.test.js
qawolf/editor/addSnippet.test.js
qawolf/helpers/global.js

// after helpers v2
qawolf/helpers/signIn.js
```

**Comment by jperl** [comment]
The second part of this is how do we manage this file syncing / saving / etc. I can think of two approaches.

A. Connect a GitHub/GitLab repo one time via settings. On the dashboard you choose which branch you want to work off of (it defaults to your main branch). When you edit a test file you click to "Save/Commit" it and that will write a commit to your current branch.

**Pros**

- Lowest friction. Create an edit tests from the dashboard without needing to install and run anything locally.
- Easy for less-technical users

**Cons**

- Cannot run it locally without a server connection to qawolf.com or a self hosted version of qawolf.

B. Update `npx qawolf` to support using the file system as the source of truth, then having the dashboard / editor read directly from your local filesystem.

**Pros**

- We could refactor our dashboard / editor and bundle it with the npm package and airgap this. Privacy conscience teams could create and maintain tests without creating an account at qawolf.com. They can opt into that later if they want the fast test infrastructure / online editing capability.

**Cons**

- More steps / higher friction. This requires running a `cli` command every time you want to create / edit tests.
- Difficult for less technical team members. Need to learn git for committing, requires installing node / dealing with potential environment issues that a hosted solution does not have.

**Comment by jperl** [comment]
Since our goal is to be the easiest tool for testing, our plan is to go with A. Let me know if you think we should be doing something differently than what I outlined above. ^

**Comment by jperl** [comment]
This is shipped 🚀
