### ISSUE TITLE
Do not prefer [type="text"] over [name="email"] in text inputs

### ISSUE THREAD

**Issue by flaurida** [qawolf/qawolf#1331]
also for `[type="email]` and `[type="tel"]`

**Comment by Vac1911** [comment]
Example form:
```
<input type="text" class="form-control" name="first_name" value="">
<input type="text" class="form-control" name="last_name" value="">
```

While using "create code" to fill the first name it added the following line:
```
await page.fill('[type="text"]', "Andrew");
```
While that does currently work because it is the first text input, it is not a unique selector.
I would expect the selector to be: [name="first_name"] as that is unique.

When filling the last name, it does use a name selector (which is unique):
```
await page.fill('[name="last_name"]', "Mellor");
```

It seems to prefer using the type over a name for every first input of any type, whether or not the type is unique.

_note: I haven't tried playing around with the order of attributes_
