### ISSUE TITLE
Characters not recognized with German keyboard layout

### ISSUE THREAD

**Issue by flaurida** [qawolf/qawolf#240]
On German (Switzerland) keyboard layout, when typing into input:
* @ and # not recognized
* some special characters like ö are typed in twice

**Workaround**:

Replace the value in code:

// replace this
await browser.type(selectors[0], "↓AltLeft↓Digit2↑Digit2↓Digit3↑Digit3↑AltLeft");

// with this
await browser.type(selectors[0], "@#ö");

**Comment by jperl** [comment]
Just figured out how to manually test this. 

1. add Swiss German input source https://support.apple.com/guide/mac-help/type-language-mac-input-sources-mchlp1406/mac
2. open the accessibility keyboard https://support.apple.com/guide/mac-help/use-the-accessibility-keyboard-mchlc74c1c9f/mac
3. change input source in toolbar to Swiss German

**Comment by jperl** [comment]
I was able to reproduce the issue here https://github.com/qawolf/swiss-keyboard-example

On the swiss keyboard you type:

- "↓AltLeft↓Digit2↑Digit2↑AltLeft" for `@`
- "↓AltLeft↓Digit3↑Digit3↑AltLeft" for `#`

The recorder properly captures the keystrokes but Puppeteer keyboard does not respect the Swiss input source when it runs the code so those key strokes end up typing nothing.

However even if Puppeteer respected the alternate input source, it is unlikely CI would be setup with that other keyboard.

Possible solution: convert non-us keyboard keystrokes to characters w/ something like https://github.com/microsoft/node-native-keymap

**Comment by jperl** [comment]
Possible solution: convert non-us keyboard keystrokes to characters w/ something like https://github.com/microsoft/node-native-keymap
https://github.com/atom/keyboard-layout

**Comment by jperl** [comment]
The issue with using one of those libraries, is that it requires extra system dependencies for linux. So someone installing qawolf on linux would need to install 

```
On Debian-based Linux: sudo apt-get install libx11-dev libxkbfile-dev
On Red Hat-based Linux: sudo yum install libx11-devel.x86_64 libxkbfile-devel.x86_64 # or .i686
On FreeBSD: sudo pkg install libX11
```

https://github.com/microsoft/node-native-keymap#installing

We could create another package`@qawolf/i18n` and let that be an optional install, where we would convert the characters if it is present?

**Comment by jperl** [comment]
Seems relevant https://hacks.mozilla.org/2017/03/internationalize-your-keyboard-controls/

**Comment by jperl** [comment]
This has been fixed and released https://github.com/qawolf/qawolf/releases/tag/v0.7.4.

Tomorrow I will try to [simplify the generated code](https://github.com/qawolf/qawolf/issues/242#issuecomment-567317558) to be prettier but at least it will work properly now.

**Comment by jperl** [comment]
The generated code is simplified now in [0.7.5](https://www.npmjs.com/package/qawolf/v/0.7.5) fixed by https://github.com/qawolf/qawolf/pull/244
