### ISSUE TITLE
Does this work with WSL?

### ISSUE THREAD

**Issue by singleparadox** [qawolf/qawolf#394]
I followed the docs and tried to run it in WSL but I get an error:

```
npx qawolf create http://todomvc.com/examples/react myFirstTest 
                                                                                                           
2020-02-11T13:51:17.397Z error: launch: failed Error: Protocol error (Target.getBrowserContexts): Target closed. 
(node:583) UnhandledPromiseRejectionWarning: Error: Protocol error (Target.getBrowserContexts): Target closed.
    at Promise (/c/Users/Documents/testing/node_modules/playwright-core/lib/chromium/crConnection.js:121:63)
    at new Promise (<anonymous>)
    at CRSession.send (/c/Users/Documents/testing/node_modules/playwright-core/lib/chromium/crConnection.js:120:16)
    at Function.connect (/c/Users/Documents/testing/node_modules/playwright-core/lib/chromium/crBrowser.js:48:68)
(node:583) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:583) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by jperl** [comment]
Thank you for reporting this, I will investigate.

**Comment by singleparadox** [comment]
@jperl Thank you!

**Comment by jperl** [comment]
@singleparadox I am installing WSL to investigate. Which distro of Linux are you using?

**Comment by singleparadox** [comment]
@jperl SLR. I'm using Ubuntu

**Comment by jperl** [comment]
I set up Ubuntu 18.04 on WSL and tried to use Playwright directly, since QA Wolf is built on top of Playwright.

```
const playwright = require('playwright');
const browser = await playwright.chromium.launch();
```

Unfortunately I ran into the same issue you did, so it seems Playwright does not support WSL. You could file an issue with them. https://github.com/microsoft/playwright

However, my recommendation is to use Windows directly and this is why:

You need to use the browser launched by QA Wolf to create a test. WSL does not support using a GUI. You can try to hack around this by installing an X server, but since it is not actually supported you will likely run into various issues  with that.

QA Wolf and Playwright both support Windows, so I suggest using Windows directly. If you prefer the Unix style command line, you can use something like Git Bash.

Please let me know if you have any further questions, I am happy to discuss this with you.

**Comment by singleparadox** [comment]
I see. That makes sense since that WSL is console only. Thank you for the effort! Closing this issue...
