### ISSUE TITLE
🏷 Material UI dropdown (native=false) generates click on body

### ISSUE THREAD

**Issue by flaurida** [qawolf/qawolf#418]
See "Age" dropdown in Code Sandbox: https://9zjd4.csb.app/

Relates to #412

**Comment by jperl** [comment]
Did some investigation, it oddly emits the click on the body instead of the element. I changed the recorder to listen for mousedown instead and the target is correct. Also the simulated click does not work so I reverted the default to not simulate, which is more inline with Playwright's API since it will use their click by default.
