### ISSUE TITLE
📝Suggestion: A single `it` block per recording

### ISSUE THREAD

**Issue by celeryclub** [qawolf/qawolf#449]
Hi again. :)

I'm curious about the rationale for putting each action inside its own `it` block. Traditional testing best practices would dictate that each `it` block can be run independently and still pass, so I'm curious what your thoughts are about how this principle applies to end-to-end testing and specifically to QAW.

Thanks!

**Comment by jperl** [comment]
We started with one statement per step, because it is easier to follow which step it failed on. We run fail fast so that it fails on the first failing block within a test. However the trade off is that it is more verbose.

We will support this with edit mode #376. In the meantime you can kind of workaround this using create --script.

**Comment by flaurida** [comment]
Thanks for all these great ideas @celeryclub 😊 looking forward to implementing them!
