### ISSUE TITLE
[Proposal] Ability to auto-record assertions like "some text" on the page

### ISSUE THREAD

**Issue by Cloudo** [qawolf/qawolf#611]
Hi. First of all, thanks for the amazing library! 

The code generation feature is awesome, but I realized that I often have to write some typical assertions manually, for example
```await expect(page).toHaveText('Clear completed');```

I think it would be nice if such assertions also could be generated automatically (for example if I click on some element with Ctrl key).

**Comment by flaurida** [comment]
Hi @Cloudo thank you for the kind words!

Thank you for the suggestion as well, it is a cool idea. I'd like to learn a bit more about your use case. What kinds of assertions do you typically write? How often?

If you're willing to jump on a call so I can understand a bit better, please let me know: laura@qawolf.com. Otherwise feel free to comment here!

**Comment by wimpheling** [comment]
Funny, I came here just to say exactly the same thing (including the Ctrl+click shortcut).

**Comment by flaurida** [comment]
Hi @wimpheling thank you for commenting :)

If you don't mind, I'll ask the same questions as before so I can learn about your use case better. I understand the idea, but want to make sure that I have the full context of the situation where this would be useful. 

If you're willing to jump on a call, please let me know: laura@qawolf.com. Otherwise feel free to comment here! Happy Friday 🎉

**Comment by Adam-Burke** [comment]
What is the recommended approach of asserting success. E.g. for a login test. Do I click on something I know is on the login page?

**Comment by jperl** [comment]
That is the way I usually do it. Do some action not possible unless the previous action was taken. In situations where that does not work, like checking a list item was deleted, then I would write code to check the list item is removed. Here are some common patterns https://playwright.dev/#version=v1.2.1&path=docs%2Fassertions.md&q=

**Comment by darabun** [comment]
For what it's worth, it looks like this issue has been resolved with this PR https://github.com/qawolf/qawolf/pull/787

**Comment by jperl** [comment]
Moved to https://github.com/qawolf/qawolf/discussions/876 since we are tracking new feature ideas there.

Also relevant, with 2.0 we added a helper that auto-waits for text `await assertText(page, "Clear completed");`  https://www.qawolf.com/docs/add-an-assertion#add-an-assertion

**Comment by jperl** [comment]
We implemented this with snippets https://www.qawolf.com/docs/create-a-test#add-a-snippet
