### ISSUE TITLE
Error: EEXIST: file already exists, mkdir 'C:\Users\Predator'

### ISSUE THREAD

**Issue by bixuiquay** [qawolf/qawolf#778]
I have a node.js and npm already
I install the following step:
 `mkdir my-awesome-project`
 `cd my-awesome-project`
 `npm init -y`
Then I run 
` npm init qawolf `
![image](https://user-images.githubusercontent.com/43947752/90234473-ed186800-de49-11ea-9795-d56bfe5ad411.png)

**Comment by jperl** [comment]
Thanks for reporting an issue, I will investigate it this morning.

**Comment by jperl** [comment]
Hello I just ran these commands on windows in powershell and it worked for me. A few things to try:

1) Use powershell instead of cmd.exe
2) It seems that node is running into a permission error.  I recommend running these commands in your user directory instead of system32 which is a system directory.
3) Run `npm init react-app my-app` to see if this is an environment issue, or a qawolf issue.

**Comment by jperl** [comment]
Talked with @bixuiquay and they resolved the environment issue
