### ISSUE TITLE
Broken for inputs that do not emit value until blur

### ISSUE THREAD

**Issue by jperl** [qawolf/qawolf#801]
On Behance when you search the input does not emit a change event until it blurs (you take another action). After taking the next action, like click, it will create another line of code and not update the search fill value.

**Comment by aldeed** [comment]
I figured out the problem here. The search input has `contenteditable="true"`. Then for the `input` event value, qawolf has this line:

```js
target.isContentEditable ? target.innerText : target.value
```

Because an `input` is self-closing, there isn't any `innerText`. In this case, `target.isContentEditable` is `true`, but `target.value` is a better choice.

Honestly, this seems like a bug in Behance UI. I don't know why you would mark an input as content editable. But since this does exist in the wild and is easy to fix, let's do it.

We could fall back to `target.value` whenever `innerText` is empty/null, but I'm not sure that would always be correct. So IMO the best fix for this is to force `target.value` to be used if target is an `input`. Which I'll do.
