### ISSUE TITLE
Environment variables v2

### ISSUE THREAD

**Issue by jperl** [qawolf/qawolf#923]
Goals

- view pre-saved environment variables 
- choose which environment variables to use when running a test
- separate environment variables from groups (for example, makes sense to reuse staging across multiple groups)

**Comment by matthewcpaul** [comment]
**Updated Details/Goals**
- Make environments and environment variables global (separate them from today's concept of groups)
- Provide a dedicated view to manage environments and variables
- Start with 2 default environments—Staging, Production—and allow users to rename them and/or create new environments
- When creating or editing a test, allow users to configure (add, edit, delete) environment variables for any environment
  - Maybe not the ability to add new environments here? (can only do this from the dedicated view)
- When creating or editing a test, allow users to choose which environment (variables) to use when running the test

**Comment by matthewcpaul** [comment]
### Workflow 1: Configure Variables
In this flow, the user can open the "Configure Variables" dialog, edit existing Variables, add new Variables, delete Variables, and switch between Environments.

Notes:
- Variable value and actions become visible on hover
- New Variable field populates at the top of the list/table (this is because the list can grow, and will become scrollable)
- When a new Variable (or an existing Variables names is changed then) is saved, it will sort alphabetically
- In this design, there's a min-height to the dialog (TBD on what this is, if there should also be a max-height, and if those should just be the same)

**Comment by matthewcpaul** [comment]
### Workflow 2: Change and edit Environments
In this flow, the user can toggle between existing Environments using the picker, and also choose to edit Environments, which allows them to create, rename, or delete Environments.

Notes:
- I'm not sure how this list should be ordered
  - My guess is users would want to drag to rearrange these instead of it being alphabetical, but we can certainly star alphabetically
- In this design, there's no list/table header because there's just one column, but we can add "Environment" if it's needed
- I purposefully chose no min-height for this one to illustrate the difference, but it should probably be the same as the Variables dialog

![change-edit-environments](https://user-images.githubusercontent.com/8001871/105413619-5e7ff200-5c04-11eb-9240-78355d11d586.gif)

**Comment by matthewcpaul** [comment]
Form validation
Given that Variable names need to be formatted `LIKE_THIS`, and that both fields are required, do we need some simple form validation here?

![image](https://user-images.githubusercontent.com/8001871/105414416-77d56e00-5c05-11eb-8a0d-b35e5b90b537.png)

**Comment by jperl** [comment]
> Form validation

We will auto-fix it for them, no need for validation.
